### ISSUE TITLE
Is TeamsFx CLI module a requirement for any app

### ISSUE THREAD

**Issue by xpazv** [microsoft/edu-assignments-apps-sample#18]
Hello,

The documentation states that you need TeamsFx CLI module to run this app. Could you please to confirm if TeamsFx CLI module is mandatory for any application that wants to appear in the Recent apps list of Assignments? 

We are developing a similar app,  following the same steps and approach as yours, that needs to be attached to an Assignment, but we are not able to make it show up in the Recent apps list.

Best regards

**Comment by jeroenjeremy** [comment]
@andreipatrascoiu Could you please help @xpazv with this issue? We're unable to progress with our app in Teams right now. Thanks so much in advance!

**Comment by andreipatrascoiu** [comment]
Hello @xpazv,

No, TeamsFx CLI module is not required for your application to run inside Assignments. TeamsFx CLI is used here in order to simplify the deployment process.

During the development process, you need to make sure that you are using the developer preview ring: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro

Also make sure that your Teams app supports tabs: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs.

Let me know if this helps!

**Comment by JamesTrenholme-Nimble** [comment]
Hi,

We are experiencing an issue where we can't see our app in the Assignments modal when trying to add it to an assignment. We can see it when we change the manifest to use the dev schema and enable open preview in teams but obviously this is not production ready. Does anyone have any idea how to make it show when not using the dev manifest schema? We have added it to the teams channel that we want to create the assignment in too.

Am I missing something in this part of the manifest:

"configurableTabs": [
        {
            "configurationUrl": "${{TAB_ENDPOINT}}",
            "scopes": ["team"],
            "canUpdateConfiguration": true,
            "context": ["channelTab"]
        }
    ],

Like I say it works with the dev schema so that suggests it's ok but just wanted to check. 

Thanks in advance

**Comment by cristobal-buenrostro** [comment]
Hi @JamesTrenholme-Nimble , I will pass this issue over to the team.

FYI, I created a new issue to track your question.
https://github.com/microsoft/edu-assignments-apps-sample/issues/42
